version: "3.9"  # Pode ser necessário verificar e usar a versão mais recente do Docker Compose

services:
  redis:
    image: redis:alpine  # Você pode alterar "latest" para uma versão específica, se preferir.
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always  # Isso garante que o container do Redis seja reiniciado automaticamente em caso de falha ou reinicialização do sistema.